sapphire: Set RELAX_USES_LIBRARY_CHECK to true
error: mismatch in the <uses-library> tags between the build system and the manifest:
        - required libraries in build system: []
                         vs. in the manifest: []
        - optional libraries in build system: []
            and missing ones in build system: []
                         vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
        - tags in the manifest (device/xiaomi/sapphire/prebuilt/app/GoogleCameraGo/GoogleCameraGo.apk):
                uses-library-not-required:'androidx.window.extensions'          uses-library-not-required:'androidx.window.sidecar'
note: the following options are available:
        - to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
        - to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
        - to fix the check, make build system properties coherent with the manifest
        - for details, see build/make/Changes.md